version: '3.8'
services:
  takeout:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      pull: true 
    container_name: takeout
    volumes:
      - ..:/app
      - go-pkg-cache:/go/pkg
      - go-build-cache:/root/.cache/go-build
    environment:
      - TZ=Asia/Shanghai
      - GOPROXY=https://goproxy.cn,direct
      - REDIS_URL=redis:6379
      - MYSQL_URL=mysql:3306
      # 添加 Kafka 环境变量（供应用程序读取）
      - KAFKA_BROKER=kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:  # 依赖 Kafka 启动后再启动应用
        condition: service_healthy
    ports:
      - "80:80"
      - "1234:1234"
    command: sleep infinity

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sky_take_out
      MYSQL_INITDB_SKIP_TZINFO: "1"  # 避免时区初始化问题
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sky_take_out
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin --binlog-do-db=hmshop
  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sky_take_out
      TZ: Asia/Shanghai
    ports:
      - "3308:3306"
    volumes:
      - mysql-slave-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --relay-log=mysql-relay-bin --read-only=1
    depends_on:
      - mysql-master
volumes:
  redis_data:
  mysql_data:
  kafka_data:
  go-pkg-cache:
  go-build-cache:
  mysql-master-data:
  mysql-slave-data: